### PR TITLE
Begin reorganization of header includes and globals

### PR DESCRIPTION
**Pull request by ethanjli**
This PR:

- Reorganizes user-configured settings and global constants & variables into a more consistent structure
- Reorganizes header includes in main.ino into a more consistent structure (alphabetized under their respective categories)
- Reformats header includes for consistency:
  - Use `#include <header.h>` for ESP32 and Arduino core headers because they're like "system" headers, which is what the angle brackets are supposed to be for
  - Use `#include "header.h"` for third-party library headers and local header files
- De-duplicates some duplicate header file `#include`s
- Changes some global variables into global constants, where it's obvious based on the variable name
- Adds `#pragma once` to the top of all header files, to prevent compilation errors for multiple definition when the same header file is included multiple times
- Changes the file extension of a file which consisted entirely of a giant C++ comment, from `.h` to `.log` (which is the conventional file extension used to record program output logs)
- Applies the Arduino IDE's auto-formatter tool to `main.ino`

Remaining tasks which need to be done before I'm ready for this PR to be merged:

- [x]  Confirm that this PR does not break compilation
- [x] Confirm that this PR does not change the functional behavior of the ESP32 software. Right now I am blocked on this because I don't know what the correctly-functioning behavior of the software is supposed to look like.

Out-of-scope for this PR (reserved for future PRs):

- We should set up documentation for installing and using a C++ code auto-formatter/linter (e.g. https://pypi.org/project/clang-format/) to check all code files for consistent style and obvious bugs, and so that all contributors can make their contributions adhere to some standard formatting style (any style will do)
- We should also run the formatter/linter as part of Github Actions on all PRs, requiring the PR to pass the format and linting checks before it's allowed to merge, to ensure that all code follows a consistent standard before merging into the master branch

### CODE REVIEW

**Comment by beniroquai** [comment]
@ethanjli many thanks for your support! I'll compile and flash the software to see if it works correctly. One observation I made with the autoformater in the Arduino IDE was that links get broken. E.g. "/led" becomes " / led". I don't know if this is a specific issue on my computer, but this would break the code of course. Did you see that as well?

**Comment by ethanjli** [comment]
It looks to me like running the Arduino IDE's autoformatter on main.ino did not cause such changes - but maybe running it on other files could cause such changes. I'll make sure to pay attention to that as I continue refactoring!

**Comment by beniroquai** [comment]
Finally I have access to another ESP32 Camera. 

*First observation:*
If the SSID provided (e.g. `Stanford`) doesn't exist, the ESP32 cannot be reconfigured from the outside - meaning: we have to reflash it. Was this the inteded behaviour? Will go through the code to see what's happening. Will keep you posted :-)

**Comment by ethanjli** [comment]
Yes, I am trying to test out the software using Access Point mode first.

**Comment by beniroquai** [comment]
Ok, I went through the updated code. It looks good to me. However, I couldn'T connect due to the updated WiFi workflow. Should I modify the code in order to make it work and re-test features?

**Comment by ethanjli** [comment]
Sure, feel free to revert the specific changes I made to the wifi configuration!

**Pull request merged**
