### PR TITLE
Add README and LICENSE for the ESP32 subdirectory

### PR DESCRIPTION
**Pull request by ethanjli**
This PR:

- Adds `ESP32/README.md` with the instructions I've followed for setup and software upload of the software which runs on the ESP32. This README also includes some stubs for documenting the configuration settings which need to be changed in the Arduino sketch before firmware upload, as well as stubs for instructions on how to operate the aspects of the software which I don't know how to use.
- Adds the MIT license in `ESP32/main/LICENSE` for the software running on the ESP32, because right now this repository does not include any LICENSE files.

Tasks we need to resolve before I'm ready for this PR to be merged:

- [x] We need to make sure that the instructions in `ESP32/README.md` are actually correct and complete. Right now I do not trust that the software behaves correctly when I follow those instructions, because the web interface seems to be broken.
- [x] We should decide how much (if any) content to delete from the root-level README.md file in this PR, if we want to reduce redundancy between that README and the one this PR adds. (Answer: this will be saved for a future PR)
- [x] If we want to add any licenses to the root-level directory (e.g. the MIT license file and/or any open hardware licenses), I can do that in this PR. (Answer: this will be saved for a future PR)
- [x] If there are small/specific changes I should make to the root-level README.md file in this PR, I can do those. (Answer: these will be saved for future PRs)

### CODE REVIEW

**Comment by beniroquai** [comment]
Hey @ethanjli the `READM` you have created looks astonishing! Thanks a lot. It is indeed an impressive documentation for the chaotic code. However, one thing is not quite correct (anymore). 
The "[static webpage](https://github.com/beniroquai/Matchboxscope/tree/69fa5333dfa10e5f6f73290beedadeefff567710/ESP32#static-web-asset-upload)"-part via the SPIFFs has been replaced with a static webpage inside the Firmware via a String. I wanted to avoid the user from hasseling with the creation of the filesystem.

Other than that it's perfect. Do you think I can simply merge it for now? We can continue writing user guides for the different use cases once the code is done.

Regarding the license, I'm fine with MIT, however, I'm not 100% firm with software licenses anymore. Usually we go for GPLv3, but MIT is also fine.

**Comment by beniroquai** [comment]
Btw. why don't you trust the software? :D

**Comment by ethanjli** [comment]
Regarding the software not working on my computer with the instructions listed in my README in this PR, I sent you a message on Slack with more details about the brokenness I'm observing - if you'd prefer, I can instead file an item on Github Issues. I'd like for us to figure out these issues with my attempt to run your code before we merge this PR, though if you'd prefer to merge this PR first we can do that.

I agree about merging this PR before we deal with the stuff about the static web assets in SPIFFS - I'll make a separate PR to remove the static web assets files as well as the README sections referencing it.

Regarding the license, I don't have strong opinions. I just used the MIT license here because that's what you have in the license file for the openUC2 repository, and you linked to that file from the root-level README for this repository. Should we change from MIT to GPL?

**Comment by beniroquai** [comment]
I agree. For now I think this PR is complete. I read through the updated README and think most of the important steps are documented now. We can add new parts once necessary. 
I'll review Slack now. Sorry for late response. Too many communication channels ;-) 

Removing SPIFFs is a good idea. That just adds additional confusion.

**Pull request merged**
